# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WetherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # VIPER
      pod 'LightRoute', :git => 'https://github.com/SpectralDragon/LightRoute.git'
      pod 'Swinject', '~>2.6.2'
      pod 'SwinjectStoryboard', '~>2.2.0'
  
  # NETWORK
      pod 'Alamofire'
      
  # LOCATION
      pod 'SwiftLocation'
      
  # UI
      pod 'lottie-ios'


end
